project:
  type: website
  output-dir: docs

website:
  title: "AnVIL Training"
  navbar:
    left:
    - text: Home
      href: index.qmd
      icon: fa-home
    - text: Quick Start
      href: quickstart.qmd
      icon: glyphicon-flash
    - text: Vignettes
      href: vignettes.qmd
      icon: glyphicon-book
    - text: Events
      href: events.qmd
      icon: glyphicon-calendar
    - text: Videos
      href: videos.qmd
      icon: glyphicon-play-circle
    - text: Get Help
      href: help.qmd
      icon: glyphicon-question-sign

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
