---
title: "AnVIL Demos"
output: html_document
---

AnVIL Demos are a monthly, virtual meeting where we highlight what you can do on AnVIL! AnVIL Demos start with a 30-minute demonstration which can cover a range of topics, from a capability of the platform to a scientific analysis powered by AnVIL. 

After the demonstration, we’ll open up the floor to answer questions about the demo as well as any general questions you might have about AnVIL.

[View Past Demos](https://youtube.com/playlist?list=PL6aYJ_0zJ4uC978C57P3TgAAfB38uy58E)

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?si=9IcLoyaQoQwOkBCm&amp;list=PL6aYJ_0zJ4uC978C57P3TgAAfB38uy58E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Upcoming Demos

Announcements about upcoming AnVIL Demos will be posted on our [community forum](https://help.anvilproject.org/c/demos/5). After the Demo, the post will be updated with a link to a recording and a summary of the Q&As. Check out the latest topic for information about our next Demo, or browse old topics to view previous Demos that interest you.

[Sign up for future Demos](https://forms.gle/7CcaLE9AM7FrYqpP7)

You can also sign up to hear about future AnVIL Demos as well as general AnVIL announcements at [bit.ly/anvil-mailing-list](http://bit.ly/anvil-mailing-list)

We’d love to showcase how you use AnVIL! If you’re interested in presenting at a future AnVIL Demos session, reach out to Natalie Kucher (nkucher3@jhu.edu).

## 2026 Demos

- January 21: [Supporting Self-Service Data Ingestion for AnVIL](https://help.anvilproject.org/t/anvil-demos-supporting-self-service-data-ingestion-for-anvil-on-january-21-2026/368)
- February 18: [Genomic analysis using seqr on AnVIL](https://help.anvilproject.org/t/anvil-demos-genomic-analysis-using-seqr-on-anvil-on-february-18-2026/371)
- March 18: [Open Discussion Forum](https://help.anvilproject.org/t/anvil-demos-open-discussion-forum-on-march-18-2026/381)
- April 15: [Open Discussion Forum](https://help.anvilproject.org/t/anvil-demos-open-discussion-forum-on-april-15-2026/387/2)
- May 20: [GREGoR Data Validation Pipelines](https://help.anvilproject.org/t/anvil-demos-data-validation-workflows-in-anvil-on-may-20-2026/388)
- June 17: [PRS Analysis in AnVIL](https://help.anvilproject.org/t/anvil-demos-polygenic-risk-score-prs-analysis-in-anvil-on-june-17-2026/393)
- July 15: [Open Discussion Forum](https://help.anvilproject.org/t/anvil-demos-open-discussion-forum-on-july-15-2026/405)
- August 19: TBD
- September 16: Demystifying Cloud Costs for AnVIL Researchers
- October 21: TBD
- November 18: TBD
- December 16: TBD


## 2025 Demos

- January 15: [Getting Started and FastQC with Galaxy on AnVIL](https://help.anvilproject.org/t/anvil-demo-getting-started-with-your-analyses-and-running-fastqc-with-galaxy-in-anvil-on-january-15-2025/253)
- February 19: [Open Discussion Forum](https://help.anvilproject.org/t/anvil-demo-open-discussion-forum-on-february-19-2025/266)
- March 19: [Variant Analysis with VRS Toolkit](https://help.anvilproject.org/t/anvil-demo-variant-analysis-using-the-vrs-toolkit-in-anvil-on-march-19-2025/284)
- April 16: [Open Discussion Forum](https://help.anvilproject.org/t/anvil-demo-open-discussion-forum-on-april-16-2025/294)
- June 18: [Getting Started on AnVIL](https://help.anvilproject.org/t/anvil-demo-getting-started-on-anvil-on-june-18-2025/310)
- July 16: [Open Discussion Forum](https://help.anvilproject.org/t/anvil-demo-open-discussion-forum-on-july-16-2025/314)
- August 20: [Open Discussion Forum](https://help.anvilproject.org/t/anvil-demo-open-discussion-forum-on-august-20-2025/331)
- September 17: [Machine Learning with Galaxy-GLEAM](https://help.anvilproject.org/t/anvil-demos-introducing-the-all-of-us-anvil-imputation-service-on-october-15-2025/354)
- October 15: [All of Us + AnVIL Imputation Service](https://help.anvilproject.org/t/anvil-demos-introducing-the-all-of-us-anvil-imputation-service-on-october-15-2025/354)
- November 19: [AnVIL meets the new security requirements under the Genomic Data Sharing Policy](https://help.anvilproject.org/t/anvil-demos-anvil-meets-the-new-security-requirements-under-the-genomic-data-sharing-policy-on-november-19-2025/358)
- December 17: [Building Cohorts with AnVIL Data Explorer](https://help.anvilproject.org/t/anvil-demos-anvil-data-explorer-building-and-exporting-dataset-cohorts-on-december-17-2025/363)


## 2024 Demos

- April 18: [Teaching on AnVIL](https://help.anvilproject.org/t/anvil-demo-setting-up-a-data-model-for-anvil-data-submission-on-october-24-2024/230)
- October 24: [Setting up a Data Model for Data Submission on AnVIL](https://help.anvilproject.org/t/anvil-demo-setting-up-a-data-model-for-anvil-data-submission-on-october-24-2024/230)

## 2023 Demos

- March 23: [Introducing AnVIL and AnVIL Demos](https://help.anvilproject.org/t/introducing-anvil-demos-starting-march-23-2023/153)
- April 27: [Using the Human Pangenome on AnVIL](https://help.anvilproject.org/t/anvil-demo-using-the-human-pangenome-on-anvil-on-april-27/156)
- May 18: [WARP Pipelines on AnVIL](https://help.anvilproject.org/t/anvil-demo-warp-pipelines-in-anvil-terra-on-may-18/161)
- June 22: [Using Data Across AnVIL Multiple Workspaces](https://help.anvilproject.org/t/anvil-demos-learn-how-to-use-data-across-multiple-anvil-workspaces-on-june-22/163)
- July 20: [Interactive Genomic Data Science with Bioconductor](https://help.anvilproject.org/t/anvil-demo-interactive-genomic-data-science-with-bioconductor-on-july-20-2023/297)
- August 31: [Galaxy on AnVIL](https://help.anvilproject.org/t/anvil-demo-running-galaxy-in-anvil-on-august-31/168)
- September 21: [Epigenetics on AnVIL](https://help.anvilproject.org/t/anvil-demo-epigenetics-in-anvil-on-september-21/173)
- October 26: [DUOS - A tour of the AnVIL’s innovative data sharing platform](https://help.anvilproject.org/t/anvil-demo-duos-a-tour-of-the-anvils-innovative-data-sharing-platform-and-how-it-can-help-your-research-on-october-26/174)
- November 16: [Machine Learning with Bioconductor: Introduction to deep learning for image classification and application of graph-based embedding for single-cell genomics](https://help.anvilproject.org/t/anvil-demo-introduction-to-deep-learning-for-image-classification-and-application-of-graph-based-embedding-for-single-cell-genomics-on-november-16/181)
- December 13: [Collecting and Subsetting SRA data](https://help.anvilproject.org/t/anvil-demo-collecting-and-subsetting-sra-data-on-december-14/183)
